Module6 task1
htmlacademy-nodejs/274253-kekstagram pull request #13
Opened 2018-10-21 18:29 UTC by iwanttobealight

2018-10-21 19:08 UTC, kovalenp requested changes
Замечания обсуждались в чате.

2018-10-22 06:59 UTC, kovalenp commented
Тесты не проходят, смотри сразу почему:

```Failed to connect to MongoDB { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]```

У тебя в .travis.yml не хватает

```
services:
  - mongodb
```

Поэтому на агенте где запускается твой билд, нет монго базы.

https://github.com/kovalenp/194424-keksobooking/blob/master/.travis.yml

2018-10-22 06:59 UTC, kovalenp commented
Тесты не проходят, смотри сразу почему:

```Failed to connect to MongoDB { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]```

У тебя в .travis.yml не хватает

```
services:
  - mongodb
```

Поэтому на агенте где запускается твой билд, нет монго базы.

https://github.com/kovalenp/194424-keksobooking/blob/master/.travis.yml

2018-10-23 15:02 UTC, kovalenp commented on package.json
> +    "mongodb": "3.1.8",
сделай уже чтобы `npm start` запускал твой сервер, зачем эта генирация данных?

2018-10-23 15:03 UTC, kovalenp commented on src/database/db.js
> +module.exports = MongoClient.connect(url).then((client) => client.db(`posts`)).catch((e) => {
Когда запускаешь сервер вылазит вот такое предупреждение:

```(node:29610) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. Touse the new parser, pass option { useNewUrlParser: true } to MongoClient.connect```

Вот тут написано как можно починить: https://stackoverflow.com/questions/50448272/avoid-current-url-string-parser-is-deprecated-warning-by-setting-usenewurlpars

2018-10-23 15:05 UTC, kovalenp commented on src/posts/route.js
> +  res.status(404).send(`Page was not found`);
Давай здесь тоже json возвращать?

В ТЗ есть формат ошибок, они везде json:
https://up.htmlacademy.ru/nodejs/2/specification#kekstagram

раздел некорректные запросы

2018-10-23 15:05 UTC, kovalenp commented on test/mock/images-store.js
> +
Внимательнее с лишними пробелами

2018-10-23 15:14 UTC, kovalenp commented on src/posts/route.js
> +  if (!postDate) {
Ты проверяешь на обязательное поле date - проверка выполнена ОК. Но date это не обязательное поле в соответствии с ТЗ:

https://up.htmlacademy.ru/nodejs/2/specification#kekstagram (Валидация входных данных)

Для даты, если не указана можно использовать `Date.now()` посмотри как реализована валидация в код и мажик:

https://github.com/htmlacademy-nodejs/code-and-magick/blob/master/src/wizards/validate.js

Там просто нужно добавить больше условий

2018-10-23 17:20 UTC, iwanttobealight commented on package.json
> +    "mongodb": "3.1.8",
ну блин)

2018-10-23 18:46 UTC, iwanttobealight commented on src/posts/route.js
> +  res.status(404).send(`Page was not found`);
не получилось(

2018-10-25 05:56 UTC, kovalenp approved these changes

2018-10-25 05:56 UTC, merged