Module3 task2
htmlacademy-nodejs/274253-kekstagram pull request #7
Opened 2018-10-06 06:33 UTC by iwanttobealight

2018-10-06 07:41 UTC, kovalenp requested changes

2018-10-06 07:41 UTC, kovalenp commented on src/modules/generator.js
> +    };
Функция генерирует одни и те же данные

2018-10-06 13:58 UTC, kovalenp commented on src/modules/generator.js
> +  description: `Generates mock json`,
Зачем это? `generator.js` это не команда, где ты это используешь?

2018-10-06 14:00 UTC, kovalenp commented on src/modules/generator.js
> +module.exports = {
Не нужно экспортировать все что ты делаешь в этом модуле.

Из задания:

```Модуль должен экспортировать функцию generateEntity
```

Т.е. ты можешь просто описать это как функцию, а в конце добавить:

```module.exports={
  generateEntry,
}

2018-10-06 14:05 UTC, kovalenp commented on src/utils.js
> +  millisecondsInWeek: 604800000,
https://up.htmlacademy.ru/nodejs/2/criteries#basic-5

Б5. Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2018-10-06 14:07 UTC, kovalenp commented on src/test/generator.test.js
> +const generator = require(`../modules/generator`);
`test` обычно находится на одном уровне с `src`, нужно перенести

2018-10-06 14:08 UTC, iwanttobealight commented on src/modules/generator.js
> +module.exports = {
да, ты прав

2018-10-06 14:11 UTC, kovalenp commented on src/utils.js
> +module.exports = {
Намешала все в кучу :( У тебя тут и `REGEXP_URL` для проверки в тестах. И `effects` которые ты используешь в генераторе.

Если уж хочется вынести это в отдельные модули:

data => то что используется в генераторе для создания данных
helper => то что ты используешь для проверок в тесте (должно быть в test/)

2018-10-06 14:13 UTC, kovalenp commented on src/test/generator.test.js
> +  it(`func have field url`, () => {
minor: `func have field` у функций не бывает filed.

2018-10-06 14:14 UTC, kovalenp commented on src/test/generator.test.js
> +    assert.strictEqual(generateEntity.scale < 100, true);
Для интереса будем считать что от 0 до 100 включительно. В генераторе тоже нужно поправить. И для лайков тоже

2018-10-06 14:15 UTC, kovalenp commented on src/test/generator.test.js
> +  it(`field hashtags have less than 5 hashtags`, () => {
а в задании "массив строк — не более 5 элементов"

2018-10-06 14:16 UTC, kovalenp commented on src/test/generator.test.js
> +    assert.strictEqual(generateEntity.description.length < 140, true);
не более 140 :)

2018-10-06 14:18 UTC, kovalenp commented on src/modules/generator.js
> +    const date = this.getRandomNum(Date.now() - utils.millisecondsInWeek, Date.now());
можно сразу возвращать объект

```return {
  'scale': getRandomNum(0, 100),
  ...
}

2018-10-06 14:24 UTC, kovalenp commented on src/modules/generator.js
> +const crypto = require(`crypto`);
Насколько я помню, академия (в частности Евгений) очень не любят когда используют сторонние пакеты. Я задал этот вопрос в чате с наставниками. Тут два варианта:

а) нет нельзя - и тогда придется переписать
б) да можно - и тогда для тебя откроется удивительный мир lodash :)

2018-10-06 14:29 UTC, kovalenp commented
Падает билд у тебя. Нужно починить.

2018-10-07 06:41 UTC, iwanttobealight commented on src/modules/generator.js
> +const crypto = require(`crypto`);
а он разве сторонний?

2018-10-07 06:52 UTC, iwanttobealight commented on src/utils.js
> +module.exports = {
я всё везде использую)

2018-10-07 09:12 UTC, kovalenp approved these changes

2018-10-07 09:12 UTC, merged