Module3 task3
htmlacademy-nodejs/274253-kekstagram pull request #8
Opened 2018-10-08 06:11 UTC by iwanttobealight

2018-10-08 06:51 UTC, kovalenp commented on src/commands/default.js
> +    rl.question(`Привет! Хочешь сгенерировать данные?))00) `.cyan, (answer) => {
`))00` ?

2018-10-08 07:09 UTC, kovalenp requested changes

2018-10-08 07:09 UTC, kovalenp commented on src/commands/default.js
> +        if (err) {
Я правильно понял, что ты ожидаешь что если файла нет - то ты ожидаешь что он выдаст ошибку и значит можно создавать новый файл?

Если да - то плохо :smile: 
```
if (err) {
  какая то логика отличная от ErrorHandling
}
```

это очень большой code smell. Не нужно так делать.

Смотри:

```
pavel@pavel-UX303UA:~/Work/htmlAcademy/274253-kekstagram(pr/iwanttobealight/8)$ node index.js
Привет! Хочешь сгенерировать данные?))00) yes
Сколько элементов хочешь создать? 2
Укажи путь до файла в котором ты хочешь сохранить данные
Данные записаны в файл
(node:6847) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open ''
(node:6847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Если задать невалидный путь, все упадет.

Наличие файла нужно проверять https://nodejs.org/api/fs.html#fs_fs_existssync_path

2018-10-08 07:09 UTC, kovalenp commented on src/commands/default.js
> +          writeToFile(path, JSON.stringify(data));
`writeToFile(path, JSON.stringify(data));`

Т.к ты использовала `promisify` то `writeToFile` возвращает тебе `Promise`.

Его надо обробатывать: или через `async / await` или `.then()` и `.reject()`

Если ты не знаешь что это такое - не переживай, об этом должны рассказывать на сегодняшней лекции.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Если знаешь  - то можно исправлять :+1:

2018-10-08 07:09 UTC, kovalenp commented on src/commands/default.js
> +    const data = generator.generateEntity(answer);
Я бы проверял тут, что задается число. Пытался создать `eee` элементов - ниче не создается :disappointed:

2018-10-08 08:11 UTC, iwanttobealight commented on src/commands/default.js
> +          writeToFile(path, JSON.stringify(data));
я знаю, просто я тупая(
спасибо

2018-10-09 07:49 UTC, kovalenp commented on src/commands/default.js
> +          writeToFile(path, JSON.stringify(data));
Нет, ты молодец :+1:

2018-10-09 07:53 UTC, kovalenp commented on src/modules/generator.js
> +    throw error;
Тут ты выбрасываешь ошибку которую не обрабатываешь потом. Получается:

```
Сколько элементов хочешь создать? Введи число e
readline.js:1021
            throw err;
            ^

Error: Количество элементов должно быть числом
    at Object.generateEntity (/home/pavel/Work/htmlAcademy/274253-kekstagram/src/modules/generator.js:45:19)
    at rl.question (/home/pavel/Work/htmlAcademy/274253-kekstagram/src/commands/default.js:16:28)
    at Interface._onLine (readline.js:280:5)
```

Два варианта:

а) ты оборачиваешь `generateEntity` в `try/catch` там где ты это вызываешь
б) ты не бросаешь тут ошибку, а выводишь в консоль сообщение о том что `Количество элементов должно быть числом` и `process.exit(1)`

2018-10-09 07:56 UTC, kovalenp commented on src/commands/default.js
> +        }
```
  try {
          await writeToFile(path, JSON.stringify(data));
        } catch (err) {
          console.log(err.message);
        }
```

Повторяемый код (ниже в `overwriteFile`). Можно это вынести в отдельный метод:

```contst writeToFileAsync = async (path, data)```

2018-10-09 08:25 UTC, kovalenp approved these changes

2018-10-09 08:25 UTC, merged